name: Post Merge

on:
    push:
        branches: [ develop ]

jobs:
    pipeline:

        runs-on: macos-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Android Lint
                run: ./gradlew lintRelease

            -   name: Unit testing
                run: ./gradlew testReleaseUnitTest

            -   name: Assemble
                run: ./gradlew assemble

            -   name: Upload Lint report
                uses: actions/upload-artifact@v2
                with:
                    name: lint-report
                    path: "**/build/reports/*.html"
